CREATE TABLE SOC (
    SOC_ID INTEGER(10),
    SOC VARCHAR2(32),
    CONSTRAINT "SOC_ID PK" PRIMARY KEY ( SOC_ID ) ENABLE
);

    CREATE TABLE CODING (
    Coding_ID INTEGER(10),
    CodingTerm VARCHAR2(32),
    CONSTRAINT "Coding_ID PK" PRIMARY KEY ( Coding_ID ) ENABLE
);

CREATE TABLE GROUP (
    GroupID INTEGER(10),
    GroupTerm VARCHAR2(32),
    CONSTRAINT "GroupID PK" PRIMARY KEY ( GroupID ) ENABLE
);

CREATE TABLE AE_REPORT (
    ReportID INTEGER(10),
    Age INTEGER(10),
    Sex VARCHAR2(1),
    ReportCity VARCHAR2(32),
    ReportState VARCHAR2(32),
    ReportCountry VARCHAR2(32),
    CONSTRAINT "ReportID PK" PRIMARY KEY ( ReportID ) ENABLE
);

CREATE TABLE ADR (
    ADR_ID INTEGER(10),
    Age0_19 float(4),
    Age20_29 float(4),
    Age30_39 float(4),
    Age40_49 float(4),
    Age50_59 float(4),
    Age60_69 float(4),
    Age70_79 float(4),
    Age80_Up float(4),
    SexM float(4),
    SexF float(4),
    Sex VARCHAR2(1),
    N_Reports INTEGER(10),
    CONSTRAINT "ADR_ID PK" PRIMARY KEY ( ADR_ID ) ENABLE
);

CREATE TABLE PROTEIN (
    Protein_ID INTEGER(10),
    ProteinName VARCHAR2(32),
    CONSTRAINT "Protein_ID PK" PRIMARY KEY ( Protein_ID ) ENABLE
);

CREATE TABLE METABOLITE (
    MetaboliteID INTEGER(10),
    MetaboliteName VARCHAR2(32),
    CONSTRAINT "MetaboliteID PK" PRIMARY KEY ( MetaboliteID ) ENABLE
);

CREATE TABLE DRUG (
    DrugID INTEGER(10),
    RxNorm VARCHAR2(32),
    GenericName VARCHAR2(32),
    LD50 DEC(4,10),
    EC50 DEC(4,10),
    IC50 DEC(4,10),
    DistributionMethod VARCHAR2(32),
    AbsorbRate DEC(4,10),
    CONSTRAINT "DrugID PK" PRIMARY KEY ( DrugID ) ENABLE
);

CREATE TABLE MOL_INT (
    MolIntID INTEGER(10),
    Kd DEC(4,10),
    CONSTRAINT "MolIntID PK" PRIMARY KEY ( MolIntID ) ENABLE
);

CREATE TABLE CODING_SUM (
    ReportID INTEGER(10),
    ADR_ID INTEGER(10),
    Coding_ID INTEGER(10),
    GroupID INTEGER(10),
    SOC_ID INTEGER(10),
    CONSTRAINT "ReportID_FK" FOREIGN KEY (ReportID) REFERENCES AE_REPORT (ReportID),
    CONSTRAINT "ADR_ID_FK" FOREIGN KEY (ADR_ID) REFERENCES ADR (ADR_ID),
    CONSTRAINT "Coding_ID_FK" FOREIGN KEY (Coding_ID) REFERENCES CODING (Coding_ID),
    CONSTRAINT "GroupID_FK" FOREIGN KEY (GroupID) REFERENCES GROUP (GroupID),
    CONSTRAINT "SOC_ID_FK" FOREIGN KEY (SOC_ID) REFERENCES SOC (SOC_ID),
);

CREATE TABLE AE_REPORTS_LIST (
    ReportID INTEGER(10),
    ADR_ID INTEGER(10),
    CONSTRAINT "ReportID_FK" FOREIGN KEY (ReportID) REFERENCES AE_REPORT (ReportID),
    CONSTRAINT "ADR_ID_FK" FOREIGN KEY (ADR_ID) REFERENCES ADR (ADR_ID),
);

CREATE TABLE DRUGS_ADR (
    DrugID INTEGER(10),
    ADR_ID INTEGER(10),
    CONSTRAINT "DrugID_FK" FOREIGN KEY (DrugID) REFERENCES DRUG (DrugID),
    CONSTRAINT "ADR_ID_FK" FOREIGN KEY (ADR_ID) REFERENCES ADR (ADR_ID),
);

CREATE TABLE DRUGS_AE (
    DrugID INTEGER(10),
    ReportID INTEGER(10),
    CONSTRAINT "DrugID_FK" FOREIGN KEY (DrugID) REFERENCES DRUG (DrugID),
    CONSTRAINT "ReportID_FK" FOREIGN KEY (ReportID) REFERENCES AE_REPORT (ReportID),
);

CREATE TABLE SYNONYM (
    MoleculeID INTEGER(10),
    SynonymName VARCHAR2(32),
    CONSTRAINT "MoleculeID1_FK" FOREIGN KEY (MoleculeID) REFERENCES DRUG (DrugID),
    CONSTRAINT "MoleculeID2_FK" FOREIGN KEY (MoleculeID) REFERENCES PROTEIN (Protein_ID),
    CONSTRAINT "MoleculeID3_FK" FOREIGN KEY (MoleculeID) REFERENCES METABOLITE (MetaboliteID),
);

CREATE TABLE DB_REF (
    MoleculeID INTEGER(10),
    DBRefID VARCHAR2(32),
    CONSTRAINT "MoleculeID1_FK" FOREIGN KEY (MoleculeID) REFERENCES DRUG (DrugID),
    CONSTRAINT "MoleculeID2_FK" FOREIGN KEY (MoleculeID) REFERENCES PROTEIN (Protein_ID),
    CONSTRAINT "MoleculeID3_FK" FOREIGN KEY (MoleculeID) REFERENCES METABOLITE (MetaboliteID),
);

CREATE TABLE MOL_TARGET (
    Source_MoleculeID INTEGER(10),
    Target_MoleculeID INTEGER(10),
    MolIntID INTEGER(10),
    CONSTRAINT "Source_MoleculeID1_FK" FOREIGN KEY (Source_MoleculeID) REFERENCES DRUG (DrugID),
    CONSTRAINT "Source_MoleculeID2_FK" FOREIGN KEY (Source_MoleculeID) REFERENCES PROTEIN (Protein_ID),
    CONSTRAINT "Source_MoleculeID3_FK" FOREIGN KEY (Source_MoleculeID) REFERENCES METABOLITE (MetaboliteID),
    CONSTRAINT "Target_MoleculeID1_FK" FOREIGN KEY (Target_MoleculeID) REFERENCES DRUG (DrugID),
    CONSTRAINT "Target_MoleculeID2_FK" FOREIGN KEY (Target_MoleculeID) REFERENCES PROTEIN (Protein_ID),
    CONSTRAINT "Target_MoleculeID3_FK" FOREIGN KEY (Target_MoleculeID) REFERENCES METABOLITE (MetaboliteID),
    CONSTRAINT "MolIntID_FK" FOREIGN KEY (MolIntID) REFERENCES MOL_INT (MolIntID),    
);